name: animatediff
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pip
  - pip:
    - diffusers==0.20.2
    - transformers==4.32.1
    - xformers==0.0.21
    - controlnet-aux==0.0.6
    - imageio==2.27.0
    - decord==0.6.0
    - gdown
    - einops
    - omegaconf
    - safetensors
    - gradio
    - wandb
